#ifndef RAPTOREUM_CHAINPARAMSSEEDS_H
#define RAPTOREUM_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the 405Coin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x55,0x5a,0xc5,0x5e}, 10226},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x55,0x5a,0xc5,0x5f}, 10226},
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // RAPTOREUM_CHAINPARAMSSEEDS_H
